# Skip execution of one or more hooks using the SKIP environment variable:
# $ SKIP=pylint git commit -m "foo"
# $ SKIP=mypy,pylint pre-commit run --all-files
#
# If want to disable all hooks while committing, use the --no-verify/-n option:
# $ git commit -n -m "foo"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      # - id: fix-byte-order-marker
      # - id: fix-encoding-pragma
      - id: check-yaml
      # - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: debug-statements
      - id: check-docstring-first
      # - id: name-tests-test
      - id: check-toml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.8.1
    hooks:
      - id: markdownlint-cli2-fix
        name: markdownlint-cli2-fix (in place fixes)
  - repo: https://github.com/leoll2/copyright_notice_precommit
    rev: 0.1.1
    hooks:
      - id: copyright-notice
        args: [--notice=COPYRIGHT]
        files: python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        # exclude: *fixtures
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --expand-star-imports
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-rhs-for-unused-variables
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (black profile, in place fixes)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black (in place fixes)
        # args: [--diff, --check]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        # language_version: python3.11
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        # disable B101 (Test for use of assert)
        args: ["-s", "B101"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
