name: build

on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD_MACOS: "bash {project}/.github/scripts/install-macos-deps.sh"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./wheelhouse/*.whl

  build-windows:
    name: "Build on Linux for Windows"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade Python packaging tools
        run: |
          pip install --upgrade pip setuptools build wheel
          python --version
          pip --version

      - name: Install dependencies
        run: sudo apt install -y mingw-w64

      - name: Build source
        run: python -m build -s

      - name: Build Windows wheel
        run: python setup.py bdist_wheel --plat-name=win_amd64 --py-limited-api=cp38 

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/*
