name: test

on:
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types:
      - completed

jobs:

  test:
    name: "Test ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      OS_NAME: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade Python packaging tools
      run: pip install --upgrade pip setuptools wheel

    - name: Show runner information
      run: |
        python --version
        pip --version

    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: artifacts
        path: dist

    - name: Install lib
      run: pip install --find-links dist/ btclib_libsecp256k1

    - name: Test
      run: python test.py
